---
- hosts: all
  gather_facts : no
  vars:
     elastic: elasticsearch-7.16.2-x86_64.rpm
     project_root: /home/drone/elk
  tasks:
    - name: Create project root if it doesn\'t exist
      ansible.builtin.file: 
        path: "{{project_root}}"
        state: directory
    - get_url:
        url="https://artifacts.elastic.co/downloads/elasticsearch/{{elastic}}"
        dest="{{project_root}}/{{elastic}}"
    - name: Check if Elastic is installed
      command: rpm -q elasticsearch
      ignore_errors: True
      register: rpm_check
 
    - name: Install
      ansible.builtin.shell: rpm -vi {{elastic}}
      when: rpm_check.rc != 0
 
    - name: Enable and Start
      ansible.builtin.service:
        name: elasticsearch
        state: started
        enabled: yes
 
    - name: Copy configuration file
      copy:
        src: ../files/etc/elasticsearch/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
 
#    - name: Configure Elasticsearch Cluster
#      lineinfile:
#        destfile: /etc/elasticsearch/elasticsearch.yml
#        regexp: 'cluster.name:'
#        line: 'cluster.name: code-maven-demo'
#
#    - name: Configure Elasticsearch Node
#      lineinfile:
#        destfile: /etc/elasticsearch/elasticsearch.yml
#        regexp: 'node.name:'
#        line: 'node.name: code-maven-elastic-1'
#
#    - name: Configure Elasticsearch Node Master
#      lineinfile:
#        destfile: /etc/elasticsearch/elasticsearch.yml
#        regexp: 'node.master:'
#        line: 'node.master: true'
#
#    - name: Configure Elasticsearch Node Data
#      lineinfile:
#        destfile: /etc/elasticsearch/elasticsearch.yml
#        regexp: 'node.data:'
#        line: 'node.data: true'
#
#    - name: Configure Elasticsearch Single-host
#      lineinfile:
#        destfile: /etc/elasticsearch/elasticsearch.yml
#        regexp: 'discovery.type:'
#        line: 'discovery.type: single-node'
 
    - name: Restart
      ansible.builtin.service:
        name: elasticsearch
        state: restarted
 
    - name: Verify Elasticsearch
      ansible.builtin.shell: curl http://localhost:9200
      register: response
    - debug: msg="{{ response.stdout }}"
 